### ISSUE TITLE
Docker Demo（进阶）

### ISSUE THREAD

**Issue by iamtomas** [iamtomas/note#22]
```
FROM IMAGE
RUN mkdir /xxx
WORKDIR /xxx
COPY . /xxx
```

> 1. 依赖 IMAGE 镜像； 2. 工作目录在容器内的 /xxx 目录；3. 打包镜像时会将源代码复制到工作目录里

```
version: '1'
services:
  db:
    image: mysql:5.5
    restart: always
    environment:
      XXX_PASSWORD: ***
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  web:
    build: .
    restart: always
    command: COMMAND
    volumes:
      - .:/xxx
    ports:
      - "PORT:PORT"
    depends_on:
      - db
```

准备好数据库数据和依赖的镜像 IMAGE 后，运行编排环境

```
docker-compose up
```
