### ISSUE TITLE
M1 开发环境

### ISSUE THREAD

**Issue by iamtomas** [iamtomas/note#35]
# brew

从官网下载（如果因网络问题拉不下来，可以下载国内的脚本）后，把镜像修改成国内

# asdf

负责多环境管理（包括 node 、ruby、go等）

```zsh
brew install asdf
```

# git

不要使用系统自带的 git

```zsh
brew install git
```

另外 M1 下通过 `brew install bash-completion` 方式无法实现 git 补全，而是采用下边方式

```zsh
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ~/.git-completion.bash

mkdir ~/.zsh

cp git-completion.bash ~/.zsh/.git-completion.bash

# ~/.zshrc
zstyle ':completion:*:*:git:*' script ~/.zsh/.git-completion.bash
fpath=(~/.zsh $fpath)
autoload -Uz compinit && compinit
```

terminal 显示 git 分支则可以采用以下方式

```zsh
# ~/.zshrc
function parse_git_branch() {
    git branch 2> /dev/null | sed -n -e 's/^\* \(.*\)/[\1]/p'
}

setopt PROMPT_SUBST
export PROMPT='%F{grey}%n%f %F{cyan}%~%f %F{green}$(parse_git_branch)%f %F{normal}$%f '
```

# mysql

```zsh
brew install mysql
```

navicat premium 16.0.9 无需注册码

# docker

```zsh
brew install docker
```

# k8s

网上查询下，下载规定版本的 docker desktop，可以通过镜像启动 k8s

# helm

```zsh
brew install helm
```

# redis

```zsh
brew install redis
```

# java

官网下载

# kafka

在 m1 芯片下通过 brew 安装始终启动不了，也确保了 java 和 zookeeper 环境存在，最后通过 docker 将 kafka 和 zookeeper 容器跑起来

```yml
---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
```

# rails

执行 `bundle exec db:create` 报错 "[grpc_c.bundle fails to load on Apple M1 (wrong architecture)](https://github.com/grpc/grpc/issues/24846)"

```zsh
bundle config set force_ruby_platform true.
bundle
```

执行`bundle` 报错 "[ld: library not found for -lzstd while bundle install for mysql2 gem Ruby on macOS Big Sur](https://stackoverflow.com/questions/67840691/ld-library-not-found-for-lzstd-while-bundle-install-for-mysql2-gem-ruby-on-mac)"

```zsh
gem install mysql2 -v '0.5.3' -- --with-opt-dir=$(brew --prefix openssl) --with-ldflags=-L/opt/homebrew/Cellar/zstd/xxx/lib
```

注意：xxx代表zstd版本

# 待补充
